game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("shit", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("dog shit", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("kill", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("kill your mom", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("dog blood", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("blood girls 18+", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i love drinking blood of girls", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("nigga", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("sex", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("cocks", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("your mom is suck", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck you", "All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("i wanna sex with you", "All")
game.Players:ReportAbuse(game.Players.LocalPlayer, "Spamming", "Spamming text!") -- this one reports
